hier = {...
	'LANK' 'LSHN' 'g' ...
	'LBHD' 'C7' 'g' ...
	'LELB' 'LUPA' 'g' ...
	'LELB' 'LSHO' 'g' ...
	'LFHD' 'LBHD' 'g' ...
	'LFRM' 'LELB' 'g' ...
	'LFWT' 'LBWT' 'g' ...
	'LFWT' 'STRN' 'g' ...
	'LHEE' 'LANK' 'g' ...
	'LKNE' 'LTHI' 'g' ...
	'LMT1' 'LANK' 'g' ...
	'LMT1' 'LMT5' 'g' ...
	'LMT5' 'LANK' 'g' ...
	'LTOE' 'LMT1' 'g' ...
	'LSHN' 'LKNE' 'g' ...
	'LSHO' 'C7' 'g' ...
	'LSHO' 'CLAV' 'g' ...
	'LTHI' 'LFWT' 'g' ...
	'LTHI' 'LBWT' 'g' ...
    'LFIN' 'LWRB' 'g' ...
    'LFIN' 'LTHMB' 'g' ...
	'LTHMB' 'LWRA' 'g' ...
	'LUPA' 'LSHO' 'g' ...
	'LUPA' 'LSHO' 'g' ...
    'LWRA' 'LFRM' 'g' ...
    'LWRA' 'LWRB' 'g' ...
	'LWRB' 'LFRM' 'g' ...
	'RANK' 'RSHN' 'r' ...
	'RBHD' 'C7' 'r' ...
	'RELB' 'RUPA' 'r' ...
	'RELB' 'RSHO' 'r' ...
	'RFHD' 'RBHD' 'r' ...
	'RFRM' 'RELB' 'r' ...
	'RFWT' 'RBWT' 'r' ...
	'RFWT' 'STRN' 'r' ...
	'RHEE' 'RANK' 'r' ...
	'RKNE' 'RTHI' 'r' ...
	'RMT1' 'RANK' 'r' ...
	'RMT1' 'RMT5' 'r' ...
	'RMT5' 'RANK' 'r' ...
	'RTOE' 'RMT1' 'r' ...
	'RSHN' 'RKNE' 'r' ...
	'RSHO' 'C7' 'r' ...
	'RSHO' 'CLAV' 'r' ...
	'RTHI' 'RFWT' 'r' ...
	'RTHI' 'RBWT' 'r' ...
    'RFIN' 'RWRB' 'r' ...
    'RFIN' 'RTHMB' 'r' ...
	'RTHMB' 'RWRA' 'r' ...
	'RUPA' 'RSHO' 'r' ...
	'RUPA' 'RSHO' 'r' ...
    'RWRA' 'RFRM' 'r' ...
    'RWRA' 'RWRB' 'r' ...
	'RWRB' 'RFRM' 'r' ...
	'RBAC' 'C7' 'r' ...
	'LBHD' 'RBHD' 'b' ...
	'LFHD' 'RFHD' 'b' ...
	'CLAV' 'STRN' 'b' ...
};

% assume the column header is in textdata
names = textdata;
new_names = regexprep(names, '^.*:(.*-[xyz])$', '$1');
base_names = regexprep(new_names(1:3:end), '^(.*)-[xyz]$', '$1');
skeleton = [];
for i = 1:3:length(hier)
  a = find(strcmp(hier{i}, base_names));
  b = find(strcmp(hier{i+1}, base_names));
  if (~isempty(a) && ~isempty(b))
    skeleton = [skeleton; a, b];
    %skeleton = [skeleton; b, a];
  end
end